export enum ResourceType {
  Currency = 'CURRENCY',
  Wood = 'WOOD',
  Food = 'FOOD',
  Mineral = 'MINERAL',
  Metal = 'METAL'
}

export enum ResourceEnum {
  Gold = 'GOLD',
  Oak = 'OAK',
  Pine = 'PINE',
  Birch = 'BIRCH',
  Eucalyptus = 'EUCALYPTUS',
  Willow = 'WILLOW',
  Teak = 'TEAK',
  EntSoul = 'ENTSOUL',
  ReanimatedEnt = 'REANIMATEDENT',
  Stone = 'STONE',
  Graphite = 'GRAPHITE',
  Limestone = 'LIMESTONE',
  Marble = 'MARBLE',
  Quartz = 'QUARTZ',
  Obsidian = 'OBSIDIAN',
  Diamond = 'DIAMOND',
  CopperOre = 'COPPERORE',
  TinOre = 'TINORE',
  BronzeIngot = 'BRONZEINGOT',
  IronOre = 'IRONORE',
  IronIngot = 'IRONINGOT',
  SteelIngot = 'STEELINGOT',
  GoldOre = 'GOLDORE',
  GoldIngot = 'GOLDINGOT',
  LatinumOre = 'LATINUMORE',
  LatinumIngot = 'LATINUMINGOT',
  UnbelieviumOre = 'UNBELIEVIUMORE',
  LustrialOre = 'LUSTRIALORE',
  SpectrusOre = 'SPECTRUSORE',
  TemprousIngot = 'TEMPROUSINGOT',
  RefinedTemprous = 'REFINEDTEMPROUS',
  Wheat = 'WHEAT',
  Bread = 'BREAD',
  RawHerring = 'RAWHERRING',
  Herring = 'HERRING',
  RawSteak = 'RAWSTEAK',
  Steak = 'STEAK'
}
